hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local

version: v1
exp_name: exp001
env: local
cv:
  n_splits: 5
  purge_gap: 5
model:
  kinds:
    - lgb
    # - cbt
    # - xgb
whole_training: true
