hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local

is_lgb_only: false
exp_name: exp001
n_splits: 5
